codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  status:
    project:
      default:
        target: 100%
    patch:
      default:
        target: 100%

comment:
  layout: "header, files, footer"
  hide_project_coverage: false
