name: Coding Standards

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
  workflow_dispatch:

env:
  PHP_VERSION: '8.3'
  TOOLS_BIN_PATH: 'vendor-bin/tool/vendor/bin'
  LOCK_FILE: 'vendor-bin/tools/composer.lock'

jobs:
  static-analysis-phpstan:
    name: Coding Standards
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          tools: cs2pr
          coverage: none

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles(env.LOCK_FILE) }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Run PHP_CodeSniffer
        run: ${{ env.TOOLS_BIN_PATH }}/phpcs -q --no-colors --report=checkstyle src tests | cs2pr
