name: Coding Standards

on:
  push:
    branches:
      - main
      - '*.x'
  pull_request:
  workflow_dispatch:

env:
  PHP_VERSION: '8.5'
  TOOLS_BIN_PATH: 'vendor-bin/tools/vendor/bin'
  LOCK_FILE: 'vendor-bin/tools/composer.lock'

jobs:
  static-analysis-phpstan:
    name: Coding Standards
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@44454db4f0199b8b9685a5d763dc37cbf79108e1 # v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          tools: cs2pr
          coverage: none

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@6f8efc29b200d32929f49075959781ed54ec270c # v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles(env.LOCK_FILE) }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Run PHP_CodeSniffer
        run: ${{ env.TOOLS_BIN_PATH }}/phpcs -q --no-colors --report=checkstyle src tests | cs2pr
